apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 543222
      targetPort: 54322
  selector:
    name: postgres-pod
    app: demo-voting-app
    