apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  template:
   metadata:
    name: myapp-rc
    labels:
      name: myapp
   spec:
    containers: 
    - name: jenkins-ci-cd-tool
      image: jenkins/jenkins
  replicas: 3 
